/mob/living/carbon/human/proc/damageCheck()
	var/damage = rand(1,6)
	switch(src.alternian_blood_type)
		if("Mutant")
			damage *= rand(0.1,0.2)
		if("Rust")
			damage *= rand(10,15)
		if("Bronze")
			damage *= rand(10,15)
		if("Gold")
			damage *= rand(10,15)
		if("Lime")
			damage *= rand(35,45)
		if("Jade")
			damage *= rand(35,45)
		if("Teal")
			damage *= rand(35,45)
		if("Cerulean")
			damage *= rand(50,65)
		if("Indigo")
			damage *= rand(100,150)
		if("Violet")
			damage *= rand(500,700)
		if("Purple")
			damage *= rand(500,700)
		if("Fuschia")
			damage *= rand(700,1000)
	return
