/mob/living/carbon/human/proc/damageCheck()
	var/damage = rand(1,6)
	switch(src.alternian_blood_type)
		if("Mutant")
			damage *= rand(0.1,0.5) //base human damage
		if("Rust")
			damage *= rand(1,10)
		if("Bronze")
			damage *= rand(5,15)
		if("Gold")
			damage *= rand(10,20)
		if("Lime")
			damage *= rand(15,25)
		if("Jade")
			damage *= rand(20,30)
		if("Teal")
			damage *= rand(25,35)
		if("Cerulean")
			damage *= rand(30,40)
		if("Indigo")
			damage *= rand(35,45)
		if("Violet")
			damage *= rand(50,60)
		if("Purple")
			damage *= rand(60,80)
		if("Fuschia")
			damage *= rand(90,100)
	return damage
